[mongodb]
mongodb.techytrees.online
[catalogue]
catalogue.techytrees.online
[cart]
cart.techytrees.online
[user]
user.techytrees.online
[redis]
redis.techytrees.online

[all:vars]
ansible_password=DevOps321

